name: Build Spring Petclinic on main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to use Node.js 20

      - name: Set up JDK 11
        uses: actions/setup-java@v4 # Updated to use Node.js 20
        with:
          distribution: 'temurin' # Required input provided
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build
