name: Build Spring Petclinic

on:
  push:
    branches:
      - main
  pull_request:

env:
  MAVEN_OPTS: "-Xmx1024m"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      JAVA_HOME: ${{ matrix.java_version }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        java_version: [adopt@1.8, adopt@11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_version }}

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
